### ISSUE TITLE
Improvement - Debugging parameters

### ISSUE THREAD

**Issue by Rominitch** [atlaste/CPPCoverage#16] opened 2017-07-04 19:17 UTC
I create a new branch on my fork VS 2017 to add support of Debugging parameters
![image](https://user-images.githubusercontent.com/29762419/27840952-9bb2ea0c-60fd-11e7-8fe7-d7694d4d9361.png)

Moreover, I have some trouble with argv[0] which not contains application name: I fix some part.

Please review and add in main project if approved.

**Comment by atlaste** [comment] 2017-07-05 07:47
Hmm, nice catch! I'm pretty sure I forgot to implement this feature (we work with MS Test because it plays nice with MSVC). On a first glance, the implementation looks just fine.

If I have a bit of time, I'll grab the pieces from your code that do the job and merge them back into the main branch. 

I would ask to make a pull request... problem is that it will probably break VS2015. Would it be possible to create a separate VS2017 sln + csproj? That way, we can simply merge everything back.

**Comment by Rominitch** [comment] 2017-07-05 08:44
Ok I will create a new branch for this feature based on your latest master.

**Comment by Rominitch** [comment] 2017-07-05 09:36
I create #16 branch on my fork based on master ONLY.

**Comment by Rominitch** [comment] 2017-07-18 16:23
Sorry I got your latest master and made merge -> I think you will haven't merge issue now !

**Comment by atlaste** [comment] 2017-07-18 18:51
Nah, the issue is that I've been terribly busy and don't know how these pull requests exactly work... so I'll probably have to invest some time to get this right.

**Comment by atlaste** [comment] 2017-08-03 10:07
Fixed the issues in my comments, merged the branch and rolled out a new visx. Thanks!

**Closed by atlaste** 2017-08-03 10:07 UTC
Labels: bug
